package com.currencymarket.command;

public enum ClientAction {
    SIGN_UP, SIGN_IN, GET_ALL_CLIENTS,
    DELETE_CLIENT, GET_PERSONAL_INFO, UPDATE,
    GET_COMPANY_STATUS, EXIT, UPDATE_COMPANY_STATUS,
    GET_COMPANY_STATUS_FOR_USER, CREATE_COMPANY,
    GET_COMPANY_SHARES, GET_MESSAGE, SEND_MESSAGE, GET_ASSETS, SELL_ASSETS,
    GET_ACTIVE_TRANSACTION, BUY_ASSETS, GET_HISTORY_OF_TRANSACTION_FOR_COMPANY,
    GET_COMPANIES, GET_WALLET_LIST, GET_WAITING_COMPANIES,
    CHANGE_PASSWORD, UPDATE_CASH, GET_WEEK_CHART_REPORT, ACTIVATE_CARD, GET_CARD, GET_CASH_FROM_CARD, GET_COMPLETED_TRANSACTION
}
